# Generated by Django 4.0.4 on 2022-07-22 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_product_global_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='count',
            new_name='quantity',
        ),
    ]
